---
abstract: 'I2C interface to LPS331AP Thermometer and Barometer using Device::SMBus'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-LPS331AP
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - inc
  package:
    - DB
provides:
  Device::Altimeter::LPS331AP:
    file: lib/Device/Altimeter/LPS331AP.pm
    version: 0.004
  Device::LPS331AP:
    file: lib/Device/LPS331AP.pm
    version: 0.004
requires:
  Device::SMBus: 0
  Moose: 0
  POSIX: 0
  constant: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/device-lps331ap/issues
  homepage: https://metacpan.org/release/Device-LPS331AP
  repository: git://github.com/shantanubhadoria/device-lps331ap.git
version: 0.004
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
